CREATE TABLE IF NOT EXISTS stamps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fortuneTellerId INT NOT NULL,
  imageUrl MEDIUMTEXT NOT NULL,
  imageKey VARCHAR(512) NOT NULL,
  name VARCHAR(100) NOT NULL DEFAULT '',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
