CREATE TABLE IF NOT EXISTS client_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientId INT NOT NULL,
  birthdate DATE,
  bloodType VARCHAR(5),
  memo TEXT,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_client_profile (clientId)
);

CREATE TABLE IF NOT EXISTS client_relations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  clientId INT NOT NULL,
  relation VARCHAR(50),
  name VARCHAR(100),
  birthdate DATE,
  memo VARCHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
